### ISSUE TITLE
Docker image is no longer available

### ISSUE THREAD

**Issue by shuaibiyy** [zalando/swagger-mock#6]
It appears the zalando/swagger-mock docker image is no longer available.

https://hub.docker.com/u/zalando/

**Comment by FrancescElies** [comment]
I would also be interested, I would like to give it a try to this project.

**Comment by hjacobs** [comment]
@shuaibiyy @FrancescElies you can also try out our Connexion Python framework which now has a `--mock=all` CLI option: http://connexion.readthedocs.io/en/latest/cli.html#running-a-mock-server

**Comment by FrancescElies** [comment]
Wonderful, just tried, seems to work fine. 

Connexion can't handle a swagger with external definitions in other files right?
I had to bundle the file before being able to run it with connexion.

Thanks for your answer, for me we could close the issue if you like.

**Comment by shuaibiyy** [comment]
@hjacobs Thanks! That should work nicely :)

I'll close this issue. I would have wanted to remove the swagger-mock script and have the "Build on your own" section of the readme replace the current installation instructions, but then I don't imagine it'd be difficult to provide a docker image in the near future.
